name: 12 SDK

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-12
    steps:
      - run: |
          mkdir -p xcode
          wget https://github.com/growtopiajaw/iPhoneOS-SDK/raw/master/build-3.sh
          wget https://github.com/growtopiajaw/iPhoneOS-SDK/raw/master/macos-12.txt
          bash build-3.sh
          
      - name: Upload release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: xcode/*.tar.xz
          tag: v1.0
          file_glob: true
          overwrite: true
